jenkins:
#   Master:
#     Image: "soundbusdeveloper/jenkinsx"
#     ImageTag: "v1.1" 
#   Persistence:
#     Size: 30Gi
  
 
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: fc277073030/builder-maven:0.1.644       
            
chartmuseum:
  enabled: false
chartmuseumServiceLink:
  enabled: true
  externalName: "chartmuseum.oifipaas.com"
  
nexus:
  enabled: false
nexusServiceLink:
  enabled: true
  externalName: "additional-svc.nexus.svc.cluster.local"
  
docker-registry:
  enabled: false
