jenkins:
  Master:
    Image: "fc277073030/jenkinsx"
    ImageTag: "latest" 
  Persistence:
    Size: 30Gi
 
  Agent:
    PodTemplates:
      Maven:
        Containers:
          Maven:
            Image: fc277073030/builder-maven:0.2.648         
            
chartmuseum:
  enabled: false
chartmuseumServiceLink:
  enabled: true
  externalName: "chartmuseum.51charts.com"
  
nexus:
  enabled: false
nexusServiceLink:
  enabled: true
  externalName: "additional-svc.nexus.svc.cluster.local"
  
docker-registry:
  enabled: false
